apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: Service9090
      networkVisibility: Project
      context: /
      port: 9090
      schemaFilePath: specs/service1.yaml
      type: REST
    - name: Service9091
      networkVisibility: Public
      context: /
      port: 9091
      schemaFilePath: specs/service2.yaml
      type: REST
