openapi: 3.0.0
info:
  title: Hello World Service 2
  version: 1.0.0
  description: API for Hello World Service running on port 9091.

servers:
  - url: http://localhost:9091

paths:
  /service2:
    get:
      summary: Get Hello World message from Service 2
      description: Returns a JSON object with a greeting message and the port number.
      responses:
        '200':
          description: >-
            Successful response
            dsadsad dsadas d asd asd
            dasdasjhg djdhgajsd  sdajshdg
          content:
            application/json:
              schema:
                type: object
                properties:
                  hello:
                    type: string
                    example: mock world 2
                  port:
                    type: integer
                    example: 9090